### ISSUE TITLE
Not loading, Fitbit Sense

### ISSUE THREAD

**Issue by KyleNERD** [aidanblack/Fitbit-ClassicClock#3]
I don’t know why, but after switching to this clock it worked fine on the Fitbit Sense for a few weeks.  (Heart rate stalling aside, see other issue log.)

Then out of the blue I got this:

![A78DA019-6B12-437C-B087-6BDF3ACB58B7](https://user-images.githubusercontent.com/87340542/125357724-e6e38200-e35f-11eb-9f98-2a21a00f226c.jpeg)

I tried the classic uninstall and reinstall.  Changing the clock face from the app.  But that didn’t fix it.  I changed the clock face from the watch itself and it has sprung back to life.

Hope that helps.

**Comment by aidanblack** [comment]
I witnessed this the other day when a friend tried to install the watch face. It never happened in testing so I need to see if I can replicate this behavior. One question- is your watch connected to an iPhone or Android device?

**Comment by aidanblack** [comment]
https://github.com/aidanblack/Fitbit-ClassicClock/commit/f588c2b1df6cd01e9abe0d749ecf4edd5e25722b commit will try to address this. Waiting for approval in the Fitbit Gallery.

After the update is approved, please close this issue if the bug is fixed.

**Comment by KyleNERD** [comment]
I have the Fitbit Sense connected to an iPad Mini 4 (iOS) rather than an iPhone.

**Comment by aidanblack** [comment]
The update has been approved. Select the watch face in the Fitbit app to download the update. I will leave these two issues open for now - let me know if the issue appears to be fixed. Thanks for the feedback!

**Comment by KyleNERD** [comment]
Installed.  I will test it for a few days and report back.  Thanks so much for looking into this.
