### ISSUE TITLE
Numbers instead of Roman numerals?

### ISSUE THREAD

**Issue by Nelliia** [aidanblack/Fitbit-ClassicClock#5]
I love this watch face! But I would like numbers instead of Roman numerals.
Do you think you can make a clock face with numbers? 😊

**Comment by aidanblack** [comment]
I have some work to do to update this watch face first. I am adding this to the list!

**Comment by aidanblack** [comment]
The update has been approved in the Fitbit Gallery. Please update and let me know what you think! The option to switch numerals is in the settings within the phone app.

Closing this issue

**Comment by Nelliia** [comment]
Wow! Thank you so much! 
I like it!
